name: pluspay
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^17.2.3
  geolocator: ^13.0.1
  fluro: ^2.0.5
  realm: ^20.0.0
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  mek_stripe_terminal: ^3.7.0
  badges: ^3.1.2
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/products/
    - assets/svgs/
    - .env
